name: Build M1 Wheels

on:
  push:
    branches:
      - main1
      - dev
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}--${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel on Mac M1
    runs-on: [m1]
    strategy:
      fail-fast: false

    steps:
    - uses: Chik-Network/actions/clean-workspace@main

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust.sh
        arch -arm64 sh rust.sh -y

    - name: Build m1 wheels
      run: |
        arch -arm64 python3 -m venv venv
        . ./venv/bin/activate
        export PATH=~/.cargo/bin:$PATH
        arch -arm64 pip install maturin
        arch -arm64 maturin build -m wheel/Cargo.toml -i python --release --strip --features=openssl

    - name: Install chik_clvm_rs wheel
      run: |
        . ./venv/bin/activate
        ls ./target/wheels/
        arch -arm64 pip install ./target/wheels/chik_clvm_rs*.whl

    - name: Install other wheels
      run: |
        . ./venv/bin/activate
        arch -arm64 python -m pip install pytest
        arch -arm64 python -m pip install blspy

    - name: install clvm & chik_clvm_tools
      run: |
        . ./venv/bin/activate
        arch -arm64 git clone https://github.com/Chik-Network/clvm.git --branch=main --single-branch
        arch -arm64 python -m pip install ./clvm

        arch -arm64 git clone https://github.com/Chik-Network/chik_clvm_tools.git --branch=main --single-branch
        arch -arm64 python -m pip install ./chik_clvm_tools

    - name: Ensure clvm, chik_clvm_rs, chik_clvm_tools are installed
      run: |
        . ./venv/bin/activate
        arch -arm64 python -c 'import clvm'
        arch -arm64 python -c 'import clvm; print(clvm.__file__)'
        arch -arm64 python -c 'import chik_clvm_rs; print(chik_clvm_rs.__file__)'
        arch -arm64 python -c 'import chik_clvm_tools; print(chik_clvm_tools.__file__)'

    - name: Run tests from clvm
      run: |
        . ./venv/bin/activate
        cd clvm
        arch -arm64 pytest tests

    - name: Run tests from chik_clvm_tools
      run: |
        . ./venv/bin/activate
        cd chik_clvm_tools
        arch -arm64 pytest tests

    - name: Run tests from wheel
      run: |
        . ./venv/bin/activate
        cd wheel/python
        pytest --import-mode append tests
        # we use `append` because otherwise the `chik_clvm_rs` source is added
        # to `sys.path` and it uses that instead of the wheel (and so
        # ignoring `chik_clvm_rs.so`, which is pretty important)

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./target/wheels

    - name: Test for secrets access
      id: check_secrets
      shell: bash
      run: |
        unset HAS_SECRET
        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
        echo "HAS_SECRET=${HAS_SECRET}" >>$GITHUB_OUTPUT
      env:
        SECRET: "${{ secrets.test_pypi_password }}"

    - name: Install twine
      run: |
        . ./venv/bin/activate
        arch -arm64 pip install twine

    - name: Publish distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags') && steps.check_secrets.outputs.HAS_SECRET
      env:
        TWINE_USERNAME: __token__
        TWINE_NON_INTERACTIVE: 1
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        . ./venv/bin/activate
        arch -arm64 twine upload --non-interactive --skip-existing --verbose 'target/wheels/*'
